paste/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView

from django.contrib.auth.views import login as login_view, logout as logout_view

from .views import *

urlpatterns = patterns('',
    url(r'^$', index_view, name="index", ),
    url(r'^my/$', index_my_view, name="index_my", ),
    url(r'^add/$', add_view, name="add", ),
    url(r'^paste/(?P<paste_pk>[-\w\d]+)/$', detail_view, name="detail", ),
    url(r'^paste/raw/(?P<paste_pk>[-\w\d]+)/$', raw_view, name="raw", ),
    url(r'^paste/(?P<paste_pk>[-\w\d]+)/edit/$', edit_view, name="edit", ),
    url(r'^paste/(?P<paste_pk>[-\w\d]+)/delete/$', delete_view, name="delete", ),
    url(r'^paste/(?P<paste_pk>[-\w\d]+)/delete-process/$', delete_process, name="delete_process", ),

    url(r'^settings/$', settings_view, name="settings", ),
    url(r'^change-password/$', change_password_view, name="change_password", ),
    url(r'^change-password/done/$', TemplateView.as_view(template_name="paste/change_password_done.html"), name="change_password_done", ),

    url(r'^login/$', login_view, name="login", ),
    url(r'^logout/$', logout_view, name="logout", ),
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r"^", include("paste.urls", namespace="paste")),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paste/models.py
from django.db import models
from django.contrib.auth.models import User


class BaseManager(models.Manager):
    def all(self):
        return super(BaseManager, self).all().order_by("-pk")

    def active(self):
        return self.all().filter(deleted=False)

class BaseModel(models.Model):
    deleted = models.BooleanField(default=False)

    objects = BaseManager()

    class Meta:
        abstract = True

class Profile(BaseModel):
    user = models.OneToOneField(User)

    def __unicode__(self):
        return u"%s" % self.user

class Paste(BaseModel):
    owner = models.ForeignKey(Profile, null=True, blank=True)

    name = models.CharField(max_length=255, default="", blank=True)
    description = models.TextField(default="", blank=True)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    private = models.BooleanField()

    def __unicode__(self):
        return u"#%s %s" % (self.pk, self.name)

    def save(self, *args, **kwargs):
        if not self.owner:
            self.private = False
        return super(Paste, self).save(*args, **kwargs)

paste/forms.py
from django import forms

from .models import Paste


class PasteForm(forms.ModelForm):
    class Meta:
        model = Paste
        exclude = ("deleted", "timestamp", "owner")

paste/views.py
import time

from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.conf import settings

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm

from .models import Paste
from .forms import PasteForm


ALLOW_ANONYMOUS_PASTES = getattr(settings, 'ALLOW_ANONYMOUS_PASTES', False)


def index_view(request, template="paste/index.html"):
    pastes = Paste.objects.active()

    return render_to_response(template,
        {
            "title": "All pastes",

            "pastes": pastes[:100],
        },
        context_instance=RequestContext(request))

@login_required
def index_my_view(request, template="paste/index.html"):
    pastes = Paste.objects.active().filter(owner=request.user.profile)

    return render_to_response(template,
        {
            "title": "My pastes",

            "pastes": pastes[:100],
        },
        context_instance=RequestContext(request))

def add_view(request, template="paste/add.html"):
    add_paste_form = PasteForm(request.POST or None)
    if not request.user.is_authenticated():
        if not ALLOW_ANONYMOUS_PASTES:
            return HttpResponseForbidden("403 Forbidden")
        del add_paste_form.fields["private"]
    if add_paste_form.is_valid():
        paste = add_paste_form.save(commit=False)
        if request.user.is_authenticated():
            paste.owner = request.user.profile
        paste.save()
        return HttpResponseRedirect(reverse("paste:detail", args=(paste.pk, )))

    return render_to_response(template,
        {
            "title": "Add paste",

            "add_paste_form": add_paste_form,
        },
        context_instance=RequestContext(request))


@login_required
def edit_view(request, paste_pk, template="paste/edit.html"):
    paste = get_object_or_404(Paste, pk=paste_pk)
    if paste.owner != request.user.profile:
        return HttpResponseForbidden("403 Forbidden")

    edit_paste_form = PasteForm(request.POST or None, instance=paste)
    if edit_paste_form.is_valid():
        edit_paste_form.save()
        return HttpResponseRedirect(reverse("paste:detail", args=(paste.pk, )))

    return render_to_response(template,
        {
            "title": "%s / edit" % paste,
            "paste": paste,

            "edit_paste_form": edit_paste_form,
        },
        context_instance=RequestContext(request))


def detail_view(request, paste_pk, template="paste/detail.html"):
    paste = get_object_or_404(Paste, pk=paste_pk, deleted=False)
    if paste.private:
        if not request.user.is_authenticated():
            return HttpResponseForbidden("403 Forbidden")
        elif paste.owner != request.user.profile:
            return HttpResponseForbidden("403 Forbidden")

    return render_to_response(template,
        {
            "title": paste,
            "paste": paste,
        },
        context_instance=RequestContext(request))

def raw_view(request, paste_pk):
    paste = get_object_or_404(Paste, pk=paste_pk, deleted=False)
    if paste.private:
        if not request.user.is_authenticated():
            return HttpResponseForbidden("403 Forbidden")
        elif paste.owner != request.user.profile:
            return HttpResponseForbidden("403 Forbidden")

    return HttpResponse(paste.content, content_type="text/plain")

@login_required
def delete_view(request, paste_pk, template="paste/delete.html"):
    paste = get_object_or_404(Paste, pk=paste_pk)
    if paste.owner != request.user.profile:
        return HttpResponseForbidden("403 Forbidden")

    return render_to_response(template,
    {
        "title": "%s / delete" % paste,
        "paste": paste,
    },
    context_instance=RequestContext(request))

@login_required
def delete_process(request, paste_pk):
    paste = get_object_or_404(Paste, pk=paste_pk)
    if paste.owner != request.user.profile:
        return HttpResponseForbidden("403 Forbidden")

    paste.deleted = True
    paste.save()
    return HttpResponseRedirect(request.GET.get("next", "/"))

@login_required
def settings_view(request, template="paste/settings.html"):
    return render_to_response(template,
        {
            "title": "Settings",
        },
        context_instance=RequestContext(request))

@login_required
def change_password_view(request, template="paste/change_password.html"):
    change_password_form = PasswordChangeForm(data=request.POST or None, user=request.user)
    if change_password_form.is_valid():
        change_password_form.save()
        return HttpResponseRedirect(reverse("paste:change_password_done"))
    return render_to_response(template,
        {
            "change_password_form": change_password_form,
        },
        context_instance=RequestContext(request))

paste/templates/paste/add.html
{% extends "base.html"%}
{% block content %}
<h2>add</h2>

<form action="{{request.path}}" method="post">
{% csrf_token %}
{% include "paste/form.html" with form=add_paste_form %}
<input type="submit" value="add">
</form>

{% endblock content %}

paste/templates/paste/change_password.html
{% extends "base.html"%}
{% block content %}
<h2>change password</h2>
<form action="{{request.path}}" method="post">
{% csrf_token %}
{% include "paste/form.html" with form=change_password_form %}
<input type="submit" value="change">
</form>
{% endblock content %}

paste/templates/paste/change_password_done.html
{% extends "base.html"%}
{% block content %}
<h2>change password done</h2>
{% endblock content %}

paste/templates/paste/delete.html
{% extends "base.html"%}
{% block content %}
<h2>{{paste}} / delete</h2>
<a href="{% url 'paste:delete_process' paste.pk %}">yes</a>
<br><br>
<a href="{% url 'paste:detail' paste.pk %}">no</a>
{% endblock content %}

paste/templates/paste/detail.html
{% extends "base.html"%}
{% block content %}
<h2>{{paste}}</h2>
<p>
    {{paste.timestamp}}
    {% if paste.private %}
        | private
    {% endif %}
    {% if paste.owner %}
        | {{paste.owner}}
    {% endif %}
</p>
<p>
    <a href="{% url "paste:raw" paste.pk %}" target="_blank">raw</a>
    {% if request.user.profile and paste.owner == request.user.profile %}
    	<a href="{% url "paste:edit" paste.pk %}">edit</a>
    	<a href="{% url "paste:delete" paste.pk %}">delete</a>
    {% endif %}
</p>
<p>{{paste.description|linebreaksbr}}</p>

<hr>

<pre><code>{{paste.content}}</code></pre>

{% endblock content %}

paste/templates/paste/edit.html
{% extends "base.html"%}
{% block content %}
<h2>{{paste}} / edit</h2>

<form action="{{request.path}}" method="post">
{% csrf_token %}
{% include "paste/form.html" with form=edit_paste_form %}
<input type="submit" value="save">
</form>

{% endblock content %}

paste/templates/paste/form.html
<table>
{% for field in form %}
    <tr valign="top">
        <td>{{field.label}}</td>
        <td>
            {{field}}
            {% if field.errors %}
            <p class="red">
                {% for error in field.errors %}
                    {{error}}<br>
                {% endfor %}
            </p>
            {% endif %}
        </td>
    </tr>
{% endfor %}
</table>

paste/templates/paste/index.html
{% extends "base.html"%}
{% block content %}
<table class="highlight" cellspacing="0" cellpadding="0">
    <tr>
        <td>id</td>
        <td>name</td>
        <td></td>
        <td>owner</td>
        <td>raw</td>
        <td>edit</td>
        <td>delete</td>
        <td>timestamp</td>
    </tr>
    {% for paste in pastes %}
        {% if not paste.private or paste.owner == request.user.profile %}
        <tr>
            <td><a href="{% url "paste:detail" paste.pk %}">#{{paste.pk}}</a></td>
            <td>
                {{paste.name}}
            </td>
            <td>
                {% if paste.private %}
                    private
                {% endif %}
            </td>
            <td>
                {% if paste.owner %}
                    {{paste.owner}}
                {% endif %}
            </td>
            <td>
                <a href="{% url "paste:raw" paste.pk %}" target="_blank">raw</a>
            </td>
            <td>
                {% if request.user.profile and paste.owner == request.user.profile %}
                    <a href="{% url "paste:edit" paste.pk %}">edit</a>
                {% endif %}
            </td>
            <td>
                {% if request.user.profile and paste.owner == request.user.profile  %}
                    <a href="{% url "paste:delete" paste.pk %}">delete</a>
                {% endif %}
            </td>
            <td>{{paste.timestamp}}</td>
        </tr>
        {% endif %}
    {% endfor %}
</table>
{% endblock content %}

paste/templates/paste/settings.html
{% extends "base.html"%}
{% block content %}
<h2>settings</h2>
<a href="{% url "paste:change_password" %}">change password</a>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% if title %}{{title}} | {% endif %}Paste</title>
        <link href="{{STATIC_URL}}favicon.png" rel="shortcut icon" />
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}main.css">
    </head>
    <body>
        {% block base_content %}
            <h1>Paste</h1>
            <p>
                <a href="/">all</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url "paste:index_my" %}">my</a>
                {% endif %}
                {% if show_add_paste %}
                    <a href="{% url "paste:add" %}">add</a>
                {% endif %}
                |
                {% if request.user.is_authenticated %}
                    {{request.user.profile}}
                    <a href="{% url "paste:settings" %}">settings</a>
                    <a href="{% url "paste:logout" %}?next=/">logout</a>
                {% else %}
                    <a href="{% url "paste:login" %}">login</a>
                {% endif %}
            </p>
            {% block content %}
            {% endblock content %}
        {% endblock base_content %}
        <hr>
        <p>Paste, source on <a href="http://github.com/ondrejsika/paste" target="_blank">GitHub</a> by <a href="http://ondrejsika.com" target="_blank">Ondrej Sika</a></p>
    </body>
</html>